export const API_URL='http://localhost:5000/'
// export const API_URLMongo='http://localhost:5001/api/'
export const API_URLMongo='http://localhost:5000/'
export const API_URLMongoAvatar='http://localhost:5000/'
// export const API_URL='http://localhost:5000/boards'
